package generator

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// ValidTypeScriptIdentifier checks if a string is a valid TypeScript identifier
// Must start with a letter, underscore, or dollar sign, followed by word characters
var ValidTypeScriptIdentifier = regexp.MustCompile(`^[a-zA-Z_$][\w$]*$`)

// ValidateIdentifier returns an error if the identifier is not valid
func ValidateIdentifier(identifier string) error {
	if identifier == "" {
		return fmt.Errorf("identifier cannot be empty")
	}
	if !ValidTypeScriptIdentifier.MatchString(identifier) {
		return fmt.Errorf("invalid TypeScript identifier: %s (must match ^[a-zA-Z_$][\\w$]*$)", identifier)
	}
	return nil
}

// CleanAndValidatePath sanitizes a file path and ensures it doesn't escape allowed directory
func CleanAndValidatePath(outputPath string, allowedDir string) (string, error) {
	// Convert allowed dir to absolute
	absAllowed, err := filepath.Abs(allowedDir)
	if err != nil {
		return "", fmt.Errorf("failed to resolve allowed directory: %w", err)
	}

	// If output path is absolute, clean and validate directly
	if filepath.IsAbs(outputPath) {
		cleaned := filepath.Clean(outputPath)
		absCleaned, err := filepath.Abs(cleaned)
		if err != nil {
			return "", fmt.Errorf("failed to resolve output path: %w", err)
		}
		// Check if path tries to escape the allowed directory
		if !strings.HasPrefix(absCleaned, absAllowed+string(filepath.Separator)) && absCleaned != absAllowed {
			return "", fmt.Errorf("path traversal detected: %s is not within %s", outputPath, allowedDir)
		}
		return cleaned, nil
	}

	// For relative paths, join with allowed dir, then clean and validate
	joined := filepath.Join(absAllowed, outputPath)
	cleaned := filepath.Clean(joined)

	// Verify the cleaned path is still within allowed dir
	if !strings.HasPrefix(cleaned, absAllowed+string(filepath.Separator)) && cleaned != absAllowed {
		return "", fmt.Errorf("path traversal detected: %s is not within %s", outputPath, allowedDir)
	}

	return cleaned, nil
}

// OpenCodeOptions contains options for OpenCode wrapper generation
type OpenCodeOptions struct {
	BinaryName string
	WorkingDir string
}

// DefaultOpenCodeOptions returns default options for OpenCode generation
func DefaultOpenCodeOptions() *OpenCodeOptions {
	return &OpenCodeOptions{
		BinaryName: "taskflow",
		WorkingDir: ".",
	}
}

// GenerateOpenCodeWrapper generates a shell script wrapper for OpenCode integration
// This allows OpenCode to call the manage-tasks binary properly
func GenerateOpenCodeWrapper(opts *OpenCodeOptions) (string, error) {
	if opts == nil {
		opts = DefaultOpenCodeOptions()
	}

	var b strings.Builder

	// Shebang
	b.WriteString("#!/bin/bash\n\n")
	b.WriteString("# OpenCode wrapper for TaskFlow CLI\n")
	b.WriteString("# Generated by manage-tasks --agent opencode\n\n")

	// Get the directory where this script is located
	b.WriteString("# Get the directory where this script is located\n")
	b.WriteString("SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\"\" && pwd)\"\n\n")

	// Determine the binary path
	b.WriteString("# Determine the binary path\n")
	b.WriteString("if [ -z \"$MANAGE_TASKS_BIN\" ]; then\n")
	b.WriteString("  MANAGE_TASKS_BIN=\"${SCRIPT_DIR}/" + opts.BinaryName + "\"\n")
	b.WriteString("fi\n\n")

	// Helper function to call the binary
	b.WriteString("# Helper function to execute manage-tasks commands\n")
	b.WriteString("manage_tasks() {\n")
	b.WriteString("  \"$MANAGE_TASKS_BIN\" \"$@\"\n")
	b.WriteString("}\n\n")

	// Parse command-line arguments and route to appropriate manage-tasks commands
	b.WriteString("# Parse command and forward to manage-tasks\n")
	b.WriteString("COMMAND=\"$1\"\n")
	b.WriteString("shift || true\n\n")

	b.WriteString("case \"$COMMAND\" in\n")
	b.WriteString("  add)\n")
	b.WriteString("    manage_tasks add \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  update)\n")
	b.WriteString("    manage_tasks update \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  complete)\n")
	b.WriteString("    manage_tasks complete \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  block)\n")
	b.WriteString("    manage_tasks block \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  list)\n")
	b.WriteString("    manage_tasks list \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  reset-timedout|reset)\n")
	b.WriteString("    manage_tasks reset-timedout \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  help|--help|-h)\n")
	b.WriteString("    manage_tasks --help\n")
	b.WriteString("    ;;\n")
	b.WriteString("  *)\n")
	b.WriteString("    manage_tasks \"$@\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("esac\n")

	return b.String(), nil
}

// GetSupportedAgents returns the list of supported agent types
func GetSupportedAgents() []string {
	return []string{
		"opencode",
	}
}
